language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
env:
  - DJANGO=1.11
  - DJANGO=2.0
install:
  - pip install -q Django==$DJANGO
  - pip install coverage
  - pip install -e git://github.com/django-nose/django-nose.git#egg=django-nose
  - pip install -q -e .
  - pip install coveralls
script:
  - python runtests.py
after_success:
  - coveralls
