language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
env:
  - DJANGO=1.7
  - DJANGO=1.8
install:
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install coverage
  - pip install -e git://github.com/django-nose/django-nose.git#egg=django-nose
  - python setup.py install
script:
  - python runtests.py